version: "3"

services: 

  backend:
    build: ./backend
    restart: always
    ports:
      - 8000:80

  proxy:
    build: ./proxy
    restart: always
    ports:
      - 80:80

  guardian:
    build: ./guardian
    restart: always
    ports:
      - 8081:80
